import { PetTransmogs } from '@/types/pet';

export const baseImageUrl = 'https://oldschool.runescape.wiki/images/';

export const petTransmogs: PetTransmogs = {
	'Ikkle hydra': [
		'Ikkle_hydra_(serpentine)',
		'Ikkle_hydra_(electric)',
		'Ikkle_hydra_(fire)',
		'Ikkle_hydra_(extinguished)',
	],
	'Callisto cub': ['Callisto_cub', 'Callisto_cub_(retro)'],
	'Pet dark core': ['Pet_dark_core', 'Pet_corporeal_critter'],
	'Baby mole': ['Baby_mole', 'Baby_mole-rat'],
	Noon: ['Noon', 'Midnight'],
	'Jal-nib-rek': ['Jal-nib-rek', 'Tzrek-zuk'],
	'Kalphite princess': ['Kalphite_princess', 'Kalphite_princess_(2nd_form)'],
	'Pet smoke devil': ['Pet_smoke_devil', 'Pet_smoke_devil_(normal)'],
	'Venenatis spiderling': [
		'Venenatis_spiderling',
		'Venenatis_spiderling_(retro)',
	],
	"Vet'ion jr.": [
		"Vet'ion_jr.",
		"Vet'ion_jr._(reborn)",
		"Vet'ion_jr._(legacy)",
		"Vet'ion_jr._(reborn,_legacy)",
	],
	Phoenix: [
		'Phoenix',
		'Phoenix_(blue)',
		'Phoenix_(green)',
		'Phoenix_(purple)',
		'Phoenix_(white)',
	],
	'Pet snakeling': [
		'Pet_snakeling',
		'Pet_snakeling_(magma)',
		'Pet_snakeling_(tanzanite)',
	],
	'Rock golem': [
		'Rock_golem',
		'Rock_golem_(tin)',
		'Rock_golem_(copper)',
		'Rock_golem_(iron)',
		'Rock_golem_(blurite)',
		'Rock_golem_(silver)',
		'Rock_golem_(coal)',
		'Rock_golem_(gold)',
		'Rock_golem_(mithril)',
		'Rock_golem_(granite)',
		'Rock_golem_(adamantite)',
		'Rock_golem_(runite)',
		'Rock_golem_(amethyst)',
		'Rock_golem_(lovakite)',
		'Rock_golem_(elemental)',
		'Rock_golem_(daeyalt)',
	],
	Tangleroot: [
		'Tangleroot',
		'Tangleroot_(crystal)',
		'Tangleroot_(dragonfruit)',
		'Tangleroot_(herb)',
		'Tangleroot_(redwood)',
		'Tangleroot_(white_lily)',
	],
	Rocky: ['Rocky', 'Ziggy', 'Red'],
	'Baby chinchompa': [
		'Baby_chinchompa_(grey)',
		'Baby_chinchompa_(red)',
		'Baby_chinchompa_(black)',
		'Baby_chinchompa_(gold)',
	],
	'Rift guardian': [
		'Rift_guardian_(fire)',
		'Rift_guardian_(air)',
		'Rift_guardian_(mind)',
		'Rift_guardian_(water)',
		'Rift_guardian_(earth)',
		'Rift_guardian_(body)',
		'Rift_guardian_(cosmic)',
		'Rift_guardian_(chaos)',
		'Rift_guardian_(nature)',
		'Rift_guardian_(law)',
		'Rift_guardian_(death)',
		'Rift_guardian_(soul)',
		'Rift_guardian_(astral)',
		'Rift_guardian_(blood)',
		'Rift_guardian_(wrath)',
	],
	"Lil' creator": ["Lil'_creator", "Lil'_destructor"],
	Muphin: ['Muphin_(ranged)', 'Muphin_(melee)', 'Muphin_(shielded)'],
	Bran: ['Bran', 'Ric'],
};
